project:
  type: website

website:
  title: "Analyzing WWE Championship Reigns: A Data-Driven Exploration"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vsri0012
format:
  html:
    theme: journal
    css: styles.css
    background-color: "#f4f4f9"
    text-color: "#333333"
    font:
      heading: "Helvetica Neue, Arial"
      body: "Georgia, serif"


