<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Varun Sridhar">
<meta name="dcterms.date" content="2022-10-04">

<title>Analyzing WWE Championship Reigns: A Data-Driven Exploration</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Analyzing WWE Championship Reigns: A Data-Driven Exploration</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Varun Sridhar</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/vsri0012"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Analyzing WWE Championship Reigns: A Data-Driven Exploration</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">news</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Varun Sridhar </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 4, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p><img src="WWE.jpg" alt="WWE Championship" style="height:400px; width:800px;"></p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The <strong>WWE Championship</strong> is one of the most prestigious titles in professional wrestling, awarded to a wrestler who wins key matches, often during major WWE events. A <strong>WWE Championship reign</strong> refers to the period during which a wrestler holds the championship title, from the time they win it until they lose it in a subsequent match.</p>
<p>This blog post explores the history of WWE Championship reigns, analyzing how the length of title reigns has evolved across different eras of wrestling. By examining historical data, we aim to uncover patterns and trends that may reveal how WWE’s approach to its championships has changed over time.</p>
</section>
<section id="problem-description" class="level1">
<h1>Problem Description</h1>
<p>The primary goal of this analysis is to identify and evaluate trends in WWE Championship reign lengths across different historical periods. We aim to determine if there are distinct patterns in reign durations, with a particular focus on whether reign lengths have decreased in recent years.</p>
<p>There has been speculation that more recent WWE Championship reigns have become shorter, possibly due to changing booking strategies or shifts in audience preferences. This analysis will investigate whether these changes are reflected in the data by comparing reign lengths across eras such as Pre-1980s, 1980s-1990s, and 2000s-present.</p>
</section>
<section id="data-description" class="level1">
<h1>Data Description</h1>
<p>The dataset used in this analysis was sourced from the publicly available <a href="https://www.kaggle.com/datasets/mdabbert/professional-wrestling-champions-wwewwf">WWE Championship Reigns Dataset</a> available on <a href="https://www.kaggle.com/">Kaggle</a>, which contains detailed historical data on WWE title reigns. The dataset provides information on various aspects of each wrestler’s reign, including the duration of the reign, the titleholder, and the era in which the title was held.</p>
<ul>
<li><strong>name</strong>: The name of the wrestler.</li>
<li><strong>reign</strong>: The reign number, indicating how many times the wrestler has held the championship.</li>
<li><strong>days</strong>: The duration of each reign in days.</li>
<li><strong>era</strong>: The historical period, categorized into Pre-1980s, 1980s-1990s, and 2000s-present.</li>
</ul>
<p>Unnecessary columns, such as <strong>date_of_death</strong>, <strong>cause_of_death</strong>, and <strong>link</strong>, were excluded from the analysis as they do not provide insights related to reign length.</p>
</section>
<section id="data-cleaning-steps" class="level1">
<h1>Data Cleaning Steps:</h1>
<p>1. <strong>Date Formatting</strong>: The date column, which records the start of each reign, was converted into a proper date format using lubridate. This step allowed the extraction of the year column, which was necessary for categorizing reigns into historical eras.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert `date` to Date format and extract 'year'</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>wrestling_data <span class="ot">&lt;-</span> wrestling_data <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">dmy</span>(date),  </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">year =</span> <span class="fu">year</span>(date))  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>2. <strong>Missing Values</strong>: A check was performed to identify missing values, particularly in the <code>days</code> column (reign duration). Reigns with missing values for <code>days</code> were filtered out, as this information is critical for analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Handle missing values as needed</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>wrestling_data <span class="ot">&lt;-</span> wrestling_data <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(days))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>3. <strong>Categorizing Eras</strong>: Wrestlers’ reigns were classified into historical eras to examine trends over time. The eras were divided into Pre-1980, 1980s-1990s, and 2000s-present based on the year of the reign.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define eras </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>wrestling_data <span class="ot">&lt;-</span> wrestling_data <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">era =</span> <span class="fu">case_when</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    year <span class="sc">&lt;</span> <span class="dv">1980</span> <span class="sc">~</span> <span class="st">"Pre-1980"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    year <span class="sc">&lt;</span> <span class="dv">2000</span> <span class="sc">~</span> <span class="st">"1980s-1990s"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"2000s and later"</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>4. <strong>Data Aggregation</strong>: The average reign length per wrestler and by era was calculated to better understand the trends. Wrestlers were also filtered to identify the top 20 wrestlers with the longest average reigns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average reign length per wrestler</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>average_reign_per_wrestler <span class="ot">&lt;-</span> wrestling_data <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_reign_length =</span> <span class="fu">mean</span>(days, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Overall average reign length</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>overall_avg_reign <span class="ot">&lt;-</span> <span class="fu">mean</span>(wrestling_data<span class="sc">$</span>days, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Average reign length by era</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>average_reign_by_era <span class="ot">&lt;-</span> wrestling_data <span class="sc">%&gt;%</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(era) <span class="sc">%&gt;%</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_reign_length =</span> <span class="fu">mean</span>(days, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to get the top 20 wrestlers with the longest average reign lengths</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>top_20_wrestlers <span class="ot">&lt;-</span> average_reign_per_wrestler <span class="sc">%&gt;%</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(avg_reign_length)) <span class="sc">%&gt;%</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">20</span>, avg_reign_length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>5. <strong>Gender Classification</strong>: For the top 20 wrestlers, a new column was created to distinguish between male and female wrestlers, enabling a comparison of reign lengths across genders.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding a gender column to the top 20 wrestlers data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>top_20_wrestlers <span class="ot">&lt;-</span> top_20_wrestlers <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"The Fabulous Moolah"</span>, <span class="st">"Rockin' Robin"</span>, <span class="st">"Sensational Sherri"</span>, </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Ronda Rousey"</span>, <span class="st">"Wendi Richter"</span>, <span class="st">"The Spider Lady"</span>) <span class="sc">~</span> <span class="st">"Female"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Male"</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="top-20-average-reign-length-male-and-female" class="level2">
<h2 class="anchored" data-anchor-id="top-20-average-reign-length-male-and-female">Top 20 Average Reign Length (Male and Female)</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-top-20-wrestlers" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-top-20-wrestlers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-top-20-wrestlers-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-top-20-wrestlers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Bar chart showing the top 20 wrestlers by average reign length, separated by gender. The chart visualizes wrestlers with the longest average reigns in days, with a gradient color scale from blue (shorter reigns) to red (longer reigns), allowing for a clear comparison between male and female wrestlers.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="figure-analysis" class="level2">
<h2 class="anchored" data-anchor-id="figure-analysis">Figure Analysis</h2>
<p><a href="#fig-top-20-wrestlers" class="quarto-xref">Figure&nbsp;1</a> visualizes the top 20 WWE wrestlers by average reign length, separated by gender. This breakdown allows for clearer comparisons between male and female wrestlers and provides insight into how reign lengths differ across gender lines.</p>
<section id="key-insights" class="level3">
<h3 class="anchored" data-anchor-id="key-insights">Key Insights</h3>
<p>1. <strong>Long Reigns Across Genders</strong></p>
<ul>
<li><p>Both men and women have wrestlers with long average reign lengths, though <strong>Bruno Sammartino</strong> and <strong>The Fabulous Moolah</strong> stand out with significantly longer reigns in their respective categories.</p></li>
<li><p><strong>Bruno Sammartino’s</strong> reign length exceeds 2,000 days, while <strong>Moolah</strong> held the title for an average of over 1,500 days, highlighting the dominance of these figures in their eras.</p></li>
</ul>
<p>2. <strong>Shorter Reigns in the Modern Era</strong></p>
<ul>
<li><p>For both genders, modern wrestlers tend to have shorter reigns compared to their earlier counterparts.</p></li>
<li><p><strong>John Cena</strong> and <strong>Ronda Rousey</strong>, despite being some of the biggest names in WWE today, have much shorter reigns than wrestlers from earlier eras.</p></li>
</ul>
<p>3. <strong>Diversity of Reign Lengths</strong></p>
<ul>
<li><p>Female wrestlers such as <strong>Sensational Sherri</strong> and <strong>Rockin’ Robin</strong> have significantly longer reigns compared to their modern-day peers, like <strong>Ronda Rousey</strong>.</p></li>
<li><p>Male wrestlers show a wider diversity in reign lengths, from long-reigning champions like <strong>Bob Backlund</strong> to modern-day wrestlers like <strong>John Cena</strong> and <strong>Brock Lesnar</strong>, who have more frequent but shorter reigns.</p></li>
</ul>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<p>This faceted analysis provides a deeper understanding of how WWE Championship reigns have evolved across genders and eras. While earlier periods, particularly the Pre-1980s, were dominated by long reigns, such as Bruno Sammartino and The Fabulous Moolah, modern eras have seen shorter, more frequent title changes, reflecting WWE’s shift towards faster-paced storytelling. Despite these trends, the diversity in reign lengths—especially among male wrestlers—indicates that while frequent title changes are the norm today, certain superstars still manage to achieve extended reigns. Overall, this analysis underscores the impact of evolving entertainment demands on WWE’s booking strategies and how champions, both male and female, have adapted to these changes over time.</p>
</section>
</section>
<section id="average-reign-by-era" class="level2">
<h2 class="anchored" data-anchor-id="average-reign-by-era">Average Reign By Era</h2>
<div class="cell">
<div id="tbl-average-reign-by-era" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-average-reign-by-era-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Table showing the average reign length by era, highlighting how reign lengths have evolved over time. The Pre-1980 era had the longest average reigns, while the 1980s-1990s and 2000s-present eras show much shorter reign lengths.
</figcaption>
<div aria-describedby="tbl-average-reign-by-era-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table showing the average reign length by era, highlighting how reign lengths have evolved over time.</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; height: 80px;">Era</th>
<th data-quarto-table-cell-role="th" style="text-align: right; height: 80px;">Average Reign Length (days)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; height: 80px;">1980s-1990s</td>
<td style="text-align: right; height: 80px;">118.4846</td>
</tr>
<tr class="even">
<td style="text-align: left; height: 80px;">2000s and later</td>
<td style="text-align: right; height: 80px;">122.5714</td>
</tr>
<tr class="odd">
<td style="text-align: left; height: 80px;">Pre-1980</td>
<td style="text-align: right; height: 80px;">331.2333</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="table-analysis" class="level2">
<h2 class="anchored" data-anchor-id="table-analysis">Table Analysis</h2>
<p><a href="#tbl-average-reign-by-era" class="quarto-xref">Table&nbsp;1</a> provides insights into how WWE Championship reign lengths have evolved over time, showcasing distinct trends across three historical eras:</p>
<section id="key-observations" class="level3">
<h3 class="anchored" data-anchor-id="key-observations">Key Observations:</h3>
<p>1. <strong>Longest Reigns in the Pre-1980 Era</strong></p>
<ul>
<li><p><strong>Pre-1980</strong> reigns average <strong>331.2 days</strong>, the longest of the three eras. This aligns with the traditional strategy of having fewer title changes, which allowed champions to hold the belt for extended periods.</p></li>
<li><p>Wrestlers like <strong>Bruno Sammartino</strong> and <strong>Bob Backlund</strong> are prime examples of champions who maintained long reigns during this era. This was likely due to the WWE’s approach at the time, where championships were used to build prestige for a few key wrestlers over many years.</p></li>
</ul>
<p>2. <strong>Shorter Reigns in the 1980s-1990s</strong></p>
<ul>
<li><p>The <strong>1980s-1990s</strong> saw a significant reduction in average reign length to <strong>118.5 days</strong>. This era marked a shift in WWE’s strategy as professional wrestling became more focused on entertainment.</p></li>
<li><p>Champions like <strong>Hulk Hogan</strong> and <strong>Randy Savage</strong> still had substantial reigns, but the frequency of title defenses and changes increased as WWE transitioned into a more dynamic and faster-paced environment, with frequent title changes to maintain excitement and audience engagement.</p></li>
</ul>
<p>3. <strong>Slight Increase in the 2000s and Beyond</strong></p>
<ul>
<li><p>In the <strong>2000s and later</strong>, the average reign length slightly increased to <strong>122.6 days</strong>, though still much shorter than the Pre-1980 era. This era reflects WWE’s adaptation to the modern entertainment landscape, where titles are frequently defended, but certain wrestlers, like <strong>John Cena</strong> and <strong>Brock Lesnar</strong>, have held longer reigns in comparison to others.</p></li>
<li><p>While the average reign length in this era is close to that of the 1980s-1990s, there is a more pronounced pattern of short, frequent reigns combined with occasional longer reigns by top stars, a reflection of modern-day booking strategies that prioritize storyline flexibility and fan engagement.</p></li>
</ul>
</section>
<section id="summary-1" class="level3">
<h3 class="anchored" data-anchor-id="summary-1">Summary:</h3>
<p>The table highlights the dramatic shift in reign lengths over the decades. While earlier eras (Pre-1980) were characterized by long, stable title reigns, the later periods (1980s onward) have seen a significant decrease in average reign lengths, reflecting changes in how WWE manages its championships. This evolution is likely driven by changing audience expectations, more frequent pay-per-view events, and the need for dynamic, fast-moving storylines.</p>
</section>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This analysis provides valuable insights into the trends of WWE Championship reign lengths across different historical periods. As explored in the <strong>Problem Description</strong>, we aimed to investigate whether reign lengths have shortened in recent years due to changes in WWE’s booking strategies and audience preferences. The data confirms that reign lengths have indeed become shorter in modern eras, with significant differences observed between the <strong>Pre-1980s</strong>, <strong>1980s-1990s</strong>, and <strong>2000s-present</strong> eras. The <strong>Pre-1980s</strong> era had the longest reigns, with champions like <strong>Bruno Sammartino</strong> holding the title for extended periods, while more recent champions, such as <strong>John Cena</strong> and <strong>Ronda Rousey</strong>, have much shorter reigns.</p>
<p>This shift reflects WWE’s adaptation to faster-paced storytelling and the evolving entertainment landscape, where frequent title changes are used to maintain fan interest. Furthermore, the analysis highlights diversity in reign lengths across both genders, with certain wrestlers, such as <strong>The Fabulous Moolah</strong> and <strong>Bob Backlund</strong>, maintaining extended reigns even in periods of rapid title changes. These findings are consistent with the broader cultural shifts in professional wrestling, as discussed by Witkowski (2020), where wrestling has evolved from long-term champions to a more dynamic and engaging spectacle.</p>
<p><strong>Academic Citation</strong>:<br>
Witkowski, T. (2020). The culture of professional wrestling: Historical and sociocultural perspectives. <em>Journal of Sport and Social Issues, 44</em>(3), 258–275.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>